language: rust
cache: cargo
os: osx
rust: stable

branches:
  only:
  - master

install:
- rustup component add rustfmt-preview
- rustup component add clippy-preview
- command -v cargo-audit >/dev/null 2>&1 || cargo install cargo-audit

script:
# build
- cargo build --no-default-features
- cargo build

# test
- cargo test

# build (but do not run) interactive tests
- cargo test --features=interactive-tests --no-run

# audit
- cargo audit

# lint
- cargo fmt --version
- cargo fmt -- --check
- cargo clippy --version
- cargo clippy

# doc build
- cargo doc --no-deps
